%% BitcoinYearScores.m

PositiveKey = {'buy', 'price', 'gold', 'mining', 'blockchain', 'cards', ...
    'wallets', 'internet', 'mobile', 'phones', 'tablets', 'donation', ...
    'charity', 'apps', 'tipping', 'approves', 'bill', 'digital', 'money', ...
    'law', 'commerce', 'store', 'receive', 'growth', 'grow', 'simple', ...
    'social', 'volume', 'transaction', 'coinbase', 'exchange', 'atms', ...
    'stable', 'value', 'economic', 'deposits', 'future', 'altcoin',...
    'investment', 'trading', 'good', 'potential', 'fiat', 'secure', ...
    'legitimate', 'profit', 'profits'};

NegativeKey = {'bot', 'privacy', 'money', 'trading', 'policy', 'exchange', ...
    'banking', 'access', 'supply', 'virtual', 'government', 'crypto', ...
    'researcher', 'free', 'dark', 'web', 'block', 'sell', 'volatile',...
    'value', 'laws', 'legal', 'regulation', 'regulators', 'decentralized' ...
    'issue', 'malware', 'torrent', 'fax', 'cryptocurrency', 'bug', ...
    'collapse', 'security', 'arbitrage', 'failure', 'gox'};

links = linkArray;

for iday = 1:365
    rating(iday) = daySum(iday, links, PositiveKey, NegativeKey);
end

ratings2014 = rating;
    
