%% BitcoinYearScores.m

links = linkArray();

PositiveKey = {'buy', 'price', 'gold', 'mining', 'blockchain', ...
    'internet', 'mobile', 'phones', 'tablets', 'donation', ...
    'charity', 'apps', 'tipping', 'approves', 'bill', 'digital', 'money', ...
    'law', 'commerce', 'store', 'receive', 'growth', 'grow', 'simple', ...
    'social', 'volume', 'transaction', 'exchange', 'atms', 'profit' ...
    'stable', 'value', 'economic', 'deposits', 'future', 'altcoin',...
    'investment', 'trading', 'good', 'potential', 'fiat', 'secure', ...
    'legitimate', 'profits'};

NegativeKey = {'bot', 'privacy', 'money', 'trading', 'policy', 'exchange', ...
    'banking', 'access', 'supply', 'virtual', 'government', 'crypto', ...
    'researcher', 'free', 'dark', 'web', 'block', 'sell', 'volatile',...
    'value', 'laws', 'legal', 'regulation', 'regulators', 'decentralized' ...
    'issue', 'malware', 'torrent', 'fax', 'cryptocurrency', 'bug', ...
    'collapse', 'security', 'arbitrage', 'failure', 'gox', 'crash', ...
    'silk', 'road', 'drugs', 'porn', 'hacked', 'dead', 'threat'};
fileID = fopen('Sentiment.txt', 'a');
for iday = 1:365
    iday
    rating(iday) = daySum(iday, links, PositiveKey, NegativeKey);
    fprintf(fileID, '%s\n', rating(iday));
end

ratings2014 = rating;
    
